i want to only this file covertn into json so whow ot do this 

C:\Users\W0024618\Desktop\Backend\src\data\controllerWithdoor.xlsx
controllername	IP_address	Door 	reader
IN-PUN-2NDFLR-ISTAR PRO	10.199.13.10	APAC_IN_PUN_2NDFLR_IDF ROOM_10:05:86 Restricted Door	in:1
		APAC_IN_PUN_2NDFLR_UPS/ELEC ROOM Restricted Door_10:05:FE	in:1
		APAC_IN_PUN_2NDFLR_RECPTION TO WORKSTATION DOOR_10:05:4B	in:1
		APAC_IN_PUN_2NDFLR_RECPTION TO WORKSTATION DOOR_10:05:4B	out:1
		APAC_IN_PUN_2NDFLR_LIFTLOBBY TO RECEPTION EMTRY DOOR_10:05:74	in:1
		APAC_IN_PUN_2NDFLR_LIFTLOBBY TO WORKSTATION DOOR_10:05:F0	                
IN-PUN-PODIUM-ISTAR PRO-01	10.199.8.20	APAC_IN-PUN-PODIUM-RED-RECREATION AREA FIRE EXIT 1-DOOR	                
		APAC_IN_PUN_PODIUM_RED_IDF ROOM-02-Restricted Door	in:1
		APAC_IN-PUN-PODIUM-MAIN PODIUM LEFT ENTRY-DOOR	in:1
		APAC_IN_PUN_PODIUM_MAIN PODIUM RIGHT ENTRY-DOOR	in:1
		APAC_IN-PUN-PODIUM-RED-RECEPTION TO WS ENTRY 1-DOOR	                
		APAC_IN_PUN_PODIUM_ST2 DOOR 1 (RED)	in:1
		APAC_IN_PUN_PODIUM_RED_MAIN LIFT LOBBY ENTRY 1-DOOR	in:1
		APAC_IN_PUN_PODIUM_RED_MAIN LIFT LOBBY ENTRY 1-DOOR	out:1
		APAC_IN_PUN_PODIUM_ST 1-DOOR 1 (RED)	in:1
		APAC_IN_PUN_PODIUM_ST 1-DOOR 1 (RED)	out:1
		APAC_IN-PUN-PODIUM-YELLOW- SERVICE PASSAGE 1 ENTRY-DOOR	                
		APAC_IN-PUN-PODIUM-YELLOW-MAIN LIFT LOBBY-DOOR	                
		APAC_IN_PUN_PODIUM_ST2 DOOR 2 (YELLOW)	in:1
		APAC_IN_PUN_PODIUM_P-1 TURNSTILE 1-DOOR	in:1
		APAC_IN_PUN_PODIUM_P-1 TURNSTILE 2-DOOR	in:1
		APAC_IN_PUN_PODIUM_P-1 TURNSTILE 3-DOOR	in:1
		APAC_IN_PUN_PODIUM_P-1 TURNSTILE 4-DOOR	in:1
		APAC_IN_PUN_PODIUM_P-1 TURNSTILE 2 -OUT DOOR	out:1
		APAC_IN_PUN-PODIUM_P-1 TURNSTILE 3 -OUT DOOR	out:1
		APAC_IN_PUN_PODIUM_P-1 TURNSTILE 1-OUT DOOR	out:1
